apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cm-file-po
  name: cm-file-po
spec:
  containers:
  - image: nginx
    name: cm-file-po
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
